apiVersion: apps/v1
kind: Deployment
metadata:
  name: devopstask04
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devopstask04
  template:
    metadata:
      labels:
        app: devopstask04
    spec:
      containers:
        - name: devopstask04
          image: shandeep04/docker_task4:latest
          ports:
            - containerPort: 80
