apiVersion: v1
kind: Service
metadata:
  name: devopstask04-service
spec:
  selector:
    app: devopstask04
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
